Fix error when running tutorial
When running the tutorial in CoLab I got 2 errors:
AttributeError: 'ObservationSpaceSpec' object has no attribute 'shape'
AttributeError: 'ObservationSpaceSpec' object has no attribute 'dtype'

so this commit does the fix