Add a custom error handler for CompilerGym import error.
This adds an explanatory message to a particularly unhelpful error
message that is raised if attempting to import CompilerGym from the
root of the source repository:

    $ python -c 'import compiler_gym'
    Traceback (most recent call last):
      File "/home/cec/src/CompilerGym/compiler_gym/__init__.py", line 22, in <module>
        from compiler_gym.util.version import __version__  # isort:skip
    ModuleNotFoundError: No module named 'compiler_gym.util.version'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/cec/src/CompilerGym/compiler_gym/__init__.py", line 26, in <module>
        raise ModuleNotFoundError(
    ModuleNotFoundError: No module named 'compiler_gym.util.version'.
    Are you running in the root of the CompilerGym repository?
    If so, please change to a different directory so that `import compiler_gym` will work.